name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 新增步骤：安装 XML 工具包
      - name: Install XML Tools
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Fix Gradle Permissions
        run: chmod +x ./gradlew

      - name: Upgrade Gradle to 8.2
        run: |
          sed -i "s|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-all.zip|g" gradle/wrapper/gradle-wrapper.properties

      - name: Update AGP to 8.2.0
        run: |
          find . -name 'build.gradle' -exec sed -i -E "s/(com\.android\.tools\.build:gradle:)[^'\"]+/\18.2.0/g" {} +

      - name: Clean Legacy Manifest Packages
        run: |
          find . -path '*/src/main/AndroidManifest.xml' -exec sed -i '/package=".*"/d' {} +
          echo "=== Manifest 清理验证 ==="
          grep -r 'package=' */src/main/AndroidManifest.xml || echo "✅ 无残留 package 属性"

      - name: Fix QuickJS Manifest
        run: |
          if [ -f "quickjs/src/main/AndroidManifest.xml" ]; then
            # 修复 exported 属性
            sed -i '/<activity/{/android:exported/!s/<activity/<activity android:exported="true"/g}' quickjs/src/main/AndroidManifest.xml
            # XML 语法校验（依赖已安装的 xmllint）
            xmllint --noout quickjs/src/main/AndroidManifest.xml || (echo "❌ XML 语法错误"; exit 1)
          fi

      - name: Inject Namespaces
        run: |
          find . -name 'build.gradle' -exec sed -i "/android {/a \    namespace 'com.github.tvbox.osc'" {} +
          echo "=== 命名空间注入验证 ==="
          grep -r "namespace 'com.github.tvbox.osc'" .

      - name: Force Dependency Versions
        run: |
          echo -e "\nallprojects {\n  configurations.all {\n    resolutionStrategy {\n      force 'com.android.tools.build:gradle:8.2.0'\n      force 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.20'\n    }\n  }\n}" >> build.gradle

      - name: Build Debug APK
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --refresh-dependencies

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
